[package]
name = "mangarip"
version = "0.1.0"
authors = ["Carlos Chacin"]
edition = "2018"

[dependencies]
url = "2.2.0"
surf = "2.1.0"
# TODO: remove unused tokio features
tokio = { version = "1", features = ["full"] }
kuchiki = "0.8.1"
futures = "0.3"
regex = "1.4"